CREATE TABLE patients(patientid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
AGE INT,
GENDER VARCHAR(6),
SYMPTOMS VARCHAR(500),
TIMES VARCHAR(500),
TEMPERATURE DECIMAL(4,2),
MEDICATION VARCHAR(500),
MORTALITY VARCHAR(5));