CREATE TABLE patients(patientid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
AGE INT,
GENDER VARCHAR(6),
SYMPTOMS VARCHAR(255),
TIMES VARCHAR(50),
TEMPERATURE DECIMAL(4,2),
MEDICATION VARCHAR(500),
MORTALITY VARCHAR(5));